#!/bin/bash

echo "=========================================="
echo "Git Push Helper Script"
echo "=========================================="
echo ""
echo "All changes have been committed locally:"
echo "  - Modified: backend/db.py, queries.py, chat.py, requirements.txt"
echo "  - Added: Documentation files and data loaders"
echo "  - Commit message: 'Migrate to Render: PostgreSQL + AWS Bedrock'"
echo ""
echo "Repository: https://github.com/likhit99/contract-intelligence-platform.git"
echo "Branch: master"
echo ""
echo "=========================================="
echo "To push to GitHub, run ONE of these options:"
echo "=========================================="
echo ""
echo "OPTION 1: Using GitHub Personal Access Token (Recommended)"
echo "-----------------------------------------------------------"
echo "1. Go to: https://github.com/settings/tokens"
echo "2. Click 'Generate new token (classic)'"
echo "3. Give it a name and select 'repo' scope"
echo "4. Copy the token"
echo "5. Run this command:"
echo ""
echo "   git push https://YOUR_TOKEN@github.com/likhit99/contract-intelligence-platform.git master"
echo ""
echo ""
echo "OPTION 2: Using GitHub CLI (if installed)"
echo "-----------------------------------------------------------"
echo "   gh auth login"
echo "   git push origin master"
echo ""
echo ""
echo "OPTION 3: Using SSH (if you have SSH key set up)"
echo "-----------------------------------------------------------"
echo "   git remote set-url origin git@github.com:likhit99/contract-intelligence-platform.git"
echo "   git push origin master"
echo ""
echo ""
echo "OPTION 4: Manual push via GitHub Desktop or Web"
echo "-----------------------------------------------------------"
echo "1. Download GitHub Desktop: https://desktop.github.com/"
echo "2. Open this repository in GitHub Desktop"
echo "3. Push the changes"
echo ""
echo "=========================================="
echo "Current Status:"
echo "=========================================="
git log --oneline -1
echo ""
git status
echo ""
echo "=========================================="
echo "Files ready to push:"
echo "=========================================="
git diff --name-status HEAD~1 HEAD
echo ""
